### ISSUE TITLE
[용기내] AndroidRuntime: FATAL EXCEPTION: main     Process: kr.ac.duksung.rebit, PID: 13179     java.lang.IndexOutOfBoundsException: Index: 6, Size: 5         at java.util.ArrayList.get(ArrayList.java:437)         at kr.ac.duksung.rebit.TogoActivity.setupEvents$lambda-5(TogoActivity.kt:138)

### ISSUE THREAD

**Issue by allzeroyou** [DSWU-Unicorn/MainProject-ReBit-Android#11]

**Comment by allzeroyou** [comment]
<에러 원인>
TodoActivity의 setupEvents()의 storeList[i] 함수.
몇개의 text data 를 넣은 리스트에서 인덱스에 없는 값을 불러와서 발생.
---------
<해결>
Try-Catch 문 사용해 예외 발생시 토스트메시지 출력.
---------
<개념>
Try는 Exception 발생이 예상되는 코드를 감싸는 블록이고,
Catch는 Exception이 발생되었을 때 실행되는 블록
Try블록에서 Exception이 발생하고 ,
Catch블록에서 해당 Exception처리를 해주면,
앱은 Crash하지 않고, 다음 코드를 실행시켜 줍니다.
(물론 Catch에서 잡아주지 못한 Exception이 발생한다면 그 때는 Crash가 나겠지요.
Try로 감싼다고 무조건 Crash를 막지는 못 합니다.)

Finally는 Exception발생과 상관없이 무조건적으로 실행되는 곳 인데요.
Try->Catch->Finally 혹은 Try->Finally순으로 실행되게 되겠지요.
여기서는 보통 리소스나 디비의 커넥션을 close하게 됩니다.
