### ISSUE TITLE
[용기내] 카카오맵 Api 장소 마커찍기

### ISSUE THREAD

**Issue by allzeroyou** [DSWU-Unicorn/MainProject-ReBit-Android#33]

**Comment by allzeroyou** [comment]
https://devtalk.kakao.com/t/api/118495
https://developers.kakao.com/docs/latest/ko/local/dev-guide
https://velog.io/@iamjm29/Android-Kakao-%EC%A7%80%EB%8F%84-API-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
https://w36495.tistory.com/m/67
https://sudeky.tistory.com/202
참고

**Comment by allzeroyou** [comment]
🔥 Pull 받으니 Build 중 에러 발생
 
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :unityLibrary.
     Required by:
         project :app
      > No matching configuration of project :unityLibrary was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.2', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':app:mergeDebugAssets'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:71)
	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
	at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:161)
	at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:129)
	at org.gradle.execution.plan.DefaultExecutionPlan.doAddNodes(DefaultExecutionPlan.java:186)
[생략]

**Comment by allzeroyou** [comment]
> 해결방법
settings.gradle(Project Settings)의 unityLibrary 주소 변경.
<img width="1411" alt="스크린샷 2023-05-09 오후 11 33 21" src="https://github.com/DSWU-Unicorn/MainProject-ReBit-Android/assets/71822139/b957384c-023b-4740-8755-2178f688c192">

**Comment by allzeroyou** [comment]
>Bug
마커 말풍선 클릭시 앱 죽음.
→    ```
override fun onCalloutBalloonOfPOIItemTouched(p0: MapView?, p1: MapPOIItem?) {
        TODO("Not yet implemented")
    }```
위 코드 구현 해야함.
- 말풍선에 `가게 이름`, `전화번호` 정도 정보 제공하면 어떨까
- 원래 마커 자체 클릭시 가게 정보 activity로 이동하는데, 말풍선 클릭 후에도 acitivty 이동하도록

<img width="1552" alt="스크린샷 2023-05-10 오전 12 01 38" src="https://github.com/DSWU-Unicorn/MainProject-ReBit-Android/assets/71822139/f25b0dca-0b2d-4436-a446-6f9edf1c8d4a">
