### ISSUE TITLE
Fix: 분리해 촬영완료 누르면 앱 종료됨

### ISSUE THREAD

**Issue by Park-EunBi** [DSWU-Unicorn/MainProject-ReBit-Android#65]
## 🌈 이슈 요약

분리해 사진 촬영 완료 버튼 누르면 동네 분리수거정보의 dialog 안뜨고 앱이 종료된다.

## ✅ 체크 리스트

- [ ] 앱 종료되는 버그 fix 필요

**Comment by Park-EunBi** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.ac.duksung.rebit, PID: 17524
    kotlin.UninitializedPropertyAccessException: lateinit property content has not been initialized
        at kr.ac.duksung.rebit.CameraActivity.onCreate$lambda-4(CameraActivity.kt:121)
        at kr.ac.duksung.rebit.CameraActivity.$r8$lambda$mWbDfa4ke7Zp1iUtO1m7OAEM_qI(Unknown Source:0)
        at kr.ac.duksung.rebit.CameraActivity$$ExternalSyntheticLambda3.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7892)
        at android.widget.TextView.performClick(TextView.java:16219)
        at android.view.View.performClickInternal(View.java:7869)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:30880)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I
